service: classify-rental-api-account
frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ${env:AWSREGION}
  profile: ${env:AWSPROFILE}
  lambdaHashingVersion: 20201221
  environment:
    CLASSIFY_RENTALS_DB: ${self:custom.ClassifyRentalsTable.name}
    APP_REGION: ${self:provider.region}
  iam:
    role:
      statements:
        - ${file(aws/iam/classifyRentalsTable.yml):ClassifyRentalsTableIAM}

resources:
  Resources:
    ClassifyRentalsTable: ${file(aws/dynamodb/classifyRentalsTable.yml):ClassifyRentalsTable}

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  account_login:
    handler: bin/account-login
    events:
      - httpApi:
          path: /account/login
          method: post
  account_signup:
    handler: bin/account-signup
    events:
      - httpApi:
          path: /account/signup
          method: post

custom:
  ClassifyRentalsTable:
    arn: !GetAtt ClassifyRentalsTable.Arn
    name: !Ref ClassifyRentalsTable
